import { Router } from 'express';
import { authRateLimiter } from '../security/rateLimit.js';

import authRoutes from '../modules/auth/routes.js';
import userRoutes from '../modules/users/routes.js';
import profileRoutes from '../modules/profile/routes.js';
import conversationRoutes from '../modules/conversations/routes.js';
import messageRoutes from '../modules/messages/routes.js';
import contactRoutes from '../modules/contacts/routes.js';
import friendRoutes from '../modules/friends/routes.js';
import blockingRoutes from '../modules/blocking/routes.js';
import presenceRoutes from '../modules/presence/routes.js';
import privacyRoutes from '../modules/privacy/routes.js';
import discoveryRoutes from '../modules/discovery/routes.js';
import groupRoutes from '../modules/groups/routes.js';
import callRoutes from '../modules/calls/routes.js';
import notificationRoutes from '../modules/notifications/routes.js';
import mediaRoutes from '../modules/media/routes.js';
import voiceNoteRoutes     from '../modules/voice-notes/routes.js';
import stickerRoutes       from '../modules/stickers/routes.js';
import gifRoutes           from '../modules/gifs/routes.js';
import contactsShareRoutes from '../modules/contacts-share/routes.js';
import locationRoutes      from '../modules/locations/routes.js';
import sessionRoutes from '../modules/sessions/routes.js';
import deviceRoutes from '../modules/devices/routes.js';
import securityRoutes from '../modules/security/routes.js';
import { authenticate } from '../middlewares/authenticate.js';
import adminRoutes from '../modules/admin/routes.js';

export const apiRouter = Router();

apiRouter.use('/auth', authRateLimiter, authRoutes);
apiRouter.use('/users', userRoutes);
apiRouter.use('/profile', profileRoutes);
apiRouter.use('/conversations', conversationRoutes);
apiRouter.use('/messages', messageRoutes);
apiRouter.use('/contacts', contactRoutes);
apiRouter.use('/friends', friendRoutes);
apiRouter.use('/blocking', blockingRoutes);
apiRouter.use('/presence', presenceRoutes);
apiRouter.use('/privacy', privacyRoutes);
apiRouter.use('/discovery', discoveryRoutes);
apiRouter.use('/groups', groupRoutes);
apiRouter.use('/calls', callRoutes);
apiRouter.use('/notifications', notificationRoutes);
apiRouter.use('/media', mediaRoutes);
apiRouter.use('/voice-notes', voiceNoteRoutes);
apiRouter.use('/stickers', stickerRoutes);
apiRouter.use('/gifs', gifRoutes);
apiRouter.use('/contacts-share', contactsShareRoutes);
apiRouter.use('/locations', locationRoutes);
apiRouter.use('/sessions', authenticate, sessionRoutes);
apiRouter.use('/devices', authenticate, deviceRoutes);
apiRouter.use('/security', authenticate, securityRoutes);
apiRouter.use('/admin', adminRoutes);
